# Build stage
FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_OPS_FACADE_URL
ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
ENV VITE_OPS_FACADE_URL=${VITE_OPS_FACADE_URL}
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx vite build

# Production stage
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
ENV PORT=3000
EXPOSE ${PORT}
CMD sh -c "serve -s dist -l ${PORT}"
