# Build stage
FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_OPS_FACADE_URL
ARG VITE_SENTRY_DSN
ARG VITE_ASPIRE_RELEASE
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT_ADMIN_PORTAL
ARG RAILWAY_GIT_COMMIT_SHA
ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
ENV VITE_OPS_FACADE_URL=${VITE_OPS_FACADE_URL}
ENV VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
ENV VITE_ASPIRE_RELEASE=${VITE_ASPIRE_RELEASE}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT_ADMIN_PORTAL=${SENTRY_PROJECT_ADMIN_PORTAL}
ENV RAILWAY_GIT_COMMIT_SHA=${RAILWAY_GIT_COMMIT_SHA}
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx vite build

# Production stage
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
COPY --from=build /app/serve.json ./serve.json
ENV PORT=3000
EXPOSE ${PORT}
CMD sh -c "serve -s dist -l ${PORT} -c /app/serve.json"
