// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const missingPublicEnv = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter(Boolean) as string[];

export const supabaseConfigStatus = {
  isValid: missingPublicEnv.length === 0,
  missingPublicEnv,
} as const;

declare global {
  interface Window {
    __ASPIRE_CONFIG_ERROR__?: {
      missingPublicEnv: string[];
      message: string;
    };
  }
}

if (!supabaseConfigStatus.isValid && typeof window !== 'undefined') {
  window.__ASPIRE_CONFIG_ERROR__ = {
    missingPublicEnv,
    message:
      'Admin portal is missing required public environment variables. Configure them in your deploy service and redeploy.',
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createUnavailableClient(reason: string): SupabaseClient<Database> {
  const throwUnavailable = (operation: string): never => {
    throw new Error(
      `[ASPIRE_CONFIG] Supabase client unavailable for "${operation}". ${reason}`,
    );
  };

  return new Proxy(
    {} as SupabaseClient<Database>,
    {
      get(_target, prop) {
        if (prop === 'auth') {
          return new Proxy(
            {},
            {
              get(_authTarget, authProp) {
                return (..._args: unknown[]) =>
                  throwUnavailable(`auth.${String(authProp)}`);
              },
            },
          );
        }

        if (prop === 'functions') {
          return {
            invoke: (..._args: unknown[]) => throwUnavailable('functions.invoke'),
          };
        }

        if (prop === 'from') {
          return (..._args: unknown[]) => ({
            insert: (..._insertArgs: unknown[]) => throwUnavailable('from.insert'),
            select: (..._selectArgs: unknown[]) => throwUnavailable('from.select'),
            update: (..._updateArgs: unknown[]) => throwUnavailable('from.update'),
            delete: (..._deleteArgs: unknown[]) => throwUnavailable('from.delete'),
          });
        }

        return (..._args: unknown[]) => throwUnavailable(String(prop));
      },
    },
  );
}

export const supabase = supabaseConfigStatus.isValid
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createUnavailableClient(
      `Missing env: ${supabaseConfigStatus.missingPublicEnv.join(', ')}`,
    );
